name: ProjectA release

on:
  workflow_dispatch:
    inputs:
      project:
        description: 'Project to release'
        required: true
        type: choice
        options:
        - ezdomain.eventsourcing
        - ezdomain.core
        default: ezdomain.eventsourcing
      versionType:
        description: 'Version type'
        required: true
        type: choice
        options:
        - major
        - minor
        - patch
        default: patch
      version:
        description: 'Initial package version (e.g. 1.0.0)'
        required: false

defaults:
  run:
    working-directory: ./

jobs:
  pack-and-publish:
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.event.inputs.version }}
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET 7
      uses: actions/setup-dotnet@v3
      with: 
        dotnet-version: 7.0.x
    - name: Check if package exists
      shell: pwsh
      run: |
        try
        {
          $response = Invoke-RestMethod -Uri https://api.nuget.org/v3-flatcontainer/${{ github.event.inputs.project }}/index.json -Method Get
          $env:VERSION = $response.versions[-1]
          echo "NuGet package latest version: $env:VERSION"
        }
        catch
        {
          echo "Package was not found in NuGet."
        }
    - name: Restore project dependencies
      run: dotnet restore 'src/ProjectA/ProjectA.csproj'
    - name: Build project
      run: dotnet build 'src/ProjectA/ProjectA.csproj' --configuration Release  --no-restore
    - name: Pack project
      run: |
        dotnet pack 'src/ProjectA/ProjectA.csproj' --configuration Release --output .nuget/ -p:PackageVersion=${{ env.VERSION }} --no-restore