name: ProjectC build

on: 
  push:
    branches: [ "**" ]
    paths:
      - 'src/ProjectA/ref/**'
      - 'src/ProjectB/src/**'

  pull_request:
    branches: [ "**" ]
    paths:
      - 'src/ProjectA/ref/**'
      - 'src/ProjectB/src/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET 7
      uses: actions/setup-dotnet@v3
      with: 
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build 'src/ProjectC/src/ProjectC.csproj'