name: ProjectA build

on: 
  release:
    types: [created]

defaults:
  run:
    working-directory: ./src/ProjectA

jobs:
  pack and publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET 7
      uses: actions/setup-dotnet@v3
      with: 
        dotnet-version: 7.0.x
    - name: Restore project dependencies
      run: dotnet restore '/src/ProjectA.csproj'
    - name: Build project
      run: dotnet build '/src/ProjectA.csproj' --configuration Release  --no-restore
    - name: Pack project
      run: |
        dotnet pack '/src/ProjectA.csproj' --configuration Release --output 'src/ProjectA/ref' --output './.nuget/'